services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: demodb_image
    container_name: demodb_container
    # ports:
    #   - "3306:3306"
    volumes:
      - demodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
    restart: always


  # demoweb:
  #   image: nginx
  #   # ports:
  #   #   - "80:80"

  demoapp:
    build: 
      context: ./Docker-files/app
    image: demoapp_image
    container_name: demoapp_container
    ports:
      - "9067:8080"
    volumes:
      - demoappdata:/usr/local/tomcat/webapps

  democache:
    image: memcached
    # ports:
    #   - "11211:11211"

  demomq:
    image: rabbitmq
    # ports:
    #   - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  

volumes:
  demodbdata: {}
  demoappdata: {}
